sumocoders/forkcms

tools/install_locale.php
This will be used to import loxale.xml files during migrations.
=> Add a tool to import locale.

src/Frontend/Modules/FormBuilder/Layout/Widgets/Form.tpl, src/Frontend/Modules/FormBuilder/Widgets/Form.php, src/Frontend/Themes/Bootstrap/Modules/FormBuilder/Layout/Widgets/Form.tpl
we need to change the action so the hash is #formbuilder{$formName} and we need to parse {$formName} when the success message is shown
=> The page will now jump to where the form was before it was submitted

src/Frontend/Themes/Bootstrap/src/Coffee/theme.coffee
remove cookiebar functionality from theme.coffee because it's included in the core already
=> remove cookiebar functionality from theme.coffee

src/Backend/Modules/Pages/Engine/Model.php, src/Backend/Modules/Pages/Js/Pages.js
When there were multiple usertemplates, they got extraIds. This caused some issues, because in different places, they were seen as widgets instead of usertemplates.
=> Do some extra fixes for multiple usertemplates.

src/Backend/Modules/Pages/Engine/Model.php, src/Frontend/Themes/Bootstrap/src/Layout/Templates/UserTemplates/Templates.json
Now you can copy themes without having to change the Templates.json file path
=> Make Templates.json use relative paths

Gemfile, src/Frontend/Themes/Bootstrap/src/Js/lib/bootstrap.js
- Update Bootstrap JS version to 3.3.5
- Set Bootstrap SASS to version 3.3.5
=> Bootstrap version

.gitignore
Tools like ack and the silver searcher will respect this format in your gitignore.
=> Use a gitignore format with better support

src/Frontend/Themes/Bootstrap/src/Layout/Templates/Footer.tpl
Re-add theme.js because it covers some basic functions every project needs.
=> Re-add theme.js

package.json, src/Frontend/Themes/Bootstrap/src/Js/index.js, src/Frontend/Themes/Bootstrap/src/Js/utilities/distribute-height.js, src/Frontend/Themes/Bootstrap/src/Js/utilities/resize.js, src/Frontend/Themes/Bootstrap/src/Layout/Sass/_bootstrap-variables.scss, src/Frontend/Themes/Bootstrap/src/Layout/Sass/screen.scss
Add new folder structure and add some default functions
=> Add new default js utilities

composer.json, composer.lock
It is already set in our sumo fork class. So we don't need it in our Fork version.
=> Remove errbit as separate dependency

src/Backend/Modules/Pages/Js/Pages.js
- Enhancement
Add an input field alt attribute for every image in usertemplates, so this is set correct
=> Add input field alt atribute for use template images

package.json, src/Frontend/Themes/Bootstrap/src/Layout/Sass/_bootstrap-variables.scss
- Enhancement
make bootstrap up to date
=> Update bootstrap sass

src/Frontend/Themes/Bootstrap/Modules/Profiles/Layout/Templates/Mails/Register.html.twig
Fixes the mail that is send when a profile is registered
=> Bugfix wrong conversion register mail template to twig

src/Frontend/Themes/Bootstrap/Modules/Location/Layout/Templates/Index.html.twig, src/Frontend/Themes/Bootstrap/Modules/Location/Layout/Widgets/Location.html.twig
=> Clean up layout location module

src/Frontend/Themes/Bootstrap/src/Layout/Sass/components/_footer.scss, src/Frontend/Themes/Bootstrap/src/Layout/Sass/screen.scss, src/Frontend/Themes/Bootstrap/src/Layout/Templates/Base.html.twig
- Enhancement
Add sticky footer mixin because it is often used
=> Add sticky footer

src/Frontend/Themes/Bootstrap/Modules/FormBuilder/Layout/Templates/Mails/Form.html.twig
=> Fix spoondate error and typo

src/Frontend/Themes/Bootstrap/src/Layout/Templates/Alerts.html.twig
=> Parse html in alert messages

src/Frontend/Themes/Bootstrap/Modules/FormBuilder/Layout/Templates/Mails/Form.html.twig
=> Add trans to labels and message in formbuilder template

src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Templates/Archive.html.twig, src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Templates/Category.html.twig, src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Templates/Detail.html.twig, src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Templates/Index.html.twig
Fixes the templates of the blog module
=> Replace the date filter by spoondate

src/Backend/Modules/Pages/Js/Pages.js, src/Frontend/Themes/Bootstrap/src/Layout/Templates/UserTemplates/test.html
=> Add background image uploader in usertemplates

src/Frontend/Themes/Bootstrap/src/Layout/Sass/_bootstrap-variables.scss
Fix the errors that the font awesome fonts are not found. The font path variabele was set wrong.
=> Add correct font awesome font path

.htaccess
Specific extra files should not be accessible.
- Feature
https://app.activecollab.com/108877/reports/assignments?modal=Task-30845-860
This PR added extra .htaccess rewrite rules to deny access to extra files added to our project setup.
=> Custom htaccess rule

Capfile, Gemfile, Gemfile.lock, app/config/capistrano/deploy.rb, app/config/capistrano/stages/production.rb, app/config/capistrano/stages/staging.rb
- Feature
* https://app.activecollab.com/108877/my-work?modal=Task-29718-45
* https://app.activecollab.com/108877/my-work?modal=Task-30648-45
* https://app.activecollab.com/108877/my-work?modal=Task-30840-860
This integrates Capistrano3 into our fork from ForkCMS
=> Capistrano 3

src/Backend/Modules/Extensions/Installer/Installer.php
We still used Y to make the theme active instead of a boolean, this resulted in an error
I also moved installing the custom theme to its own custom method
=> Move installing the custom theme into a separate method and make the templates active

Gemfile, Gemfile.lock
- Enhancement
Update capistrano-forkcms so we have migrations and some other bits and bobs
=> Update capistrano-forkcms so we have migrations

src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Article.html.twig, src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Detail.html.twig
Blog image on staging were not showing because the blog folder is with a capital
=> Use capital for folder blog to blog image

src/Frontend/Themes/Bootstrap4/src/Layout/Sass/components/_forms.scss, src/Frontend/Themes/Bootstrap4/src/Layout/Sass/screen.scss
fixes #132 
Fix the form validation styling temporally
=> Add BS4 form validation styling

src/Backend/Modules/Extensions/Installer/Installer.php
=> Overwrite default template

src/Frontend/Themes/Bootstrap4/Modules/Mailmotor/Layout/Widgets/Subscribe.html.twig
You had to submit your email in the widget and after that also in de action.
Use symfony form in subscribe widget
=> Update mailmotor widget layout

src/Frontend/Themes/Bootstrap4/Modules/Mailmotor/Layout/Templates/Subscribe.html.twig, src/Frontend/Themes/Bootstrap4/Modules/Mailmotor/Layout/Templates/Unsubscribe.html.twig
Error messages were not rendered
=> Show error messages mailmotor subscribe/unsubscribe

src/Frontend/Themes/Bootstrap4/src/Layout/Sass/components/_forms.scss, src/Frontend/Themes/Bootstrap4/src/Layout/Templates/FormLayout.html.twig
- Enhancement
Label in symfony forms didn't start with a capital
Error styling layout was wrong
=> Add form layout default styling

src/Frontend/Themes/Bootstrap4/src/Js/Index.js, src/Frontend/Themes/Bootstrap4/src/Js/Theme/Pagination.js, src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Pagination.html.twig
- Enhancement
Make the pagination more user friendly on mobile
=> Add pagination for mobile

src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Base.html.twig, src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Notifications.html.twig
fix link for screenreaders to skip to the content
=> Fix link skip to content for screenreaders

src/Frontend/Themes/Bootstrap4/Modules/FormBuilder/Layout/Templates/Mails/Form.html.twig
Fix html entites in formbuilder e-mails
=> Fix formbuilder mail html entities

src/Backend/Modules/Pages/Js/Pages.js, src/Frontend/Themes/Bootstrap4/src/Layout/Templates/UserTemplates/test.html
Fix that image block optional can also be false or removed
=> Fix data-ft-block-optional can also be false of removed

src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Breadcrumb.html.twig
- Enhancement
Add screen readers only guiding text for the breadcrumb
=> Add sr-only text for the breadcrumb

src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Notifications.html.twig
- Enhancement
Center content of the cookiebar, you the brand color to fit in the theme
=> Update layout cookiebar

Gemfile.lock
So console commands, like import of migration locale, is run in prod env.
=> Update capistrano-forkcms gem

src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Notifications.html.twig
- Enhancement
Improve accessibility of the cookiebar
=> Add aria label on cookiebar close button

src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Navbar.html.twig
- Enhancement
Improve accessibility by removing the role navgition on the main nav list. Because de nav - tag says enough.
=> Remove role on nav list

src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Article.html.twig
- Enhancement
Improve accessibility by removing not correct role main on article elements in blog
=> Remove role main on blog article items

src/Frontend/Themes/Bootstrap4/src/Layout/Templates/FormLayout.html.twig
Remove double closing label tag
=> Remove double label closing tag

src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Article.html.twig
=> Fix typo itemscope

src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Article.html.twig
It's not allowed to have 2 the same attributes
=> Remove double attribute itemprop

src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Archive.html.twig, src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Article.html.twig, src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Detail.html.twig, src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Widgets/RecentComments.html.twig
=> Use timezone designation

src/Frontend/Themes/Bootstrap4/Modules/Location/Layout/Templates/Index.html.twig
The map was never initialised. Made it work by adding the correct data attributes.
=> Make map location index work

src/Frontend/Themes/Bootstrap4/Modules/FormBuilder/Layout/Widgets/Form.html.twig
- Enhancement
Add layout to render recaptcha in formbuilder widget
=> Render recaptcha in formbuild widget

package-lock.json, package.json, src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Archive.html.twig, src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Article.html.twig, src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Detail.html.twig, src/Frontend/Themes/Bootstrap4/Modules/Faq/Layout/Templates/Category.html.twig, src/Frontend/Themes/Bootstrap4/Modules/Faq/Layout/Templates/Detail.html.twig, src/Frontend/Themes/Bootstrap4/src/Js/Index.js, src/Frontend/Themes/Bootstrap4/src/Layout/Sass/screen.scss, src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Notifications.html.twig, src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Pagination.html.twig
- Enhancement
Use Font Awesome 5
=> Upgrade to font awesome 5

src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Navigation.html.twig
=> Remove wrong role navigation that is not valid

src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Footer.html.twig
- Enhancement
It did not open in a new tab, now it does
=> Open sumocoders link in a new tab

app/config/capistrano/stages/staging.rb
=> Update staging server defaults to PHP 7.2

src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Article.html.twig
- Enhancement
None, just cleaner code.
Cleaner code.
=> Get rid of spaces that should not be there

src/Frontend/Themes/Bootstrap4/src/Js/Theme/Pagination.js
Parameter pairs should not override each other.
=> Upgrade get params of mobile pagination

src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Footer.html.twig
role navigation should not be on a ul
=> Remove wrong role navigation on ul

src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Base.html.twig
- Enhancement
missing quotes in meta tag twitter:og
=> Add missing quote

src/Frontend/Themes/Bootstrap4/Modules/Profiles/Layout/Widgets/LoginLink.html.twig
- Enhancement
Use If else statement instead of 2 if statements
=> Use If else statement instead of 2 if statements

.stylelintignore, .stylelintrc, package-lock.json, package.json, src/Frontend/Themes/Bootstrap4/src/Layout/Sass/_bootstrap-variables.scss
- Enhancement
Fix errors for stylelint on bootstrap variables file.
Fix errors for stylelint on bootstrap variables file.
=> Variables style

.gitlab-ci.yml, app/config/capistrano/stages/staging.rb
- Feature
Changes the default version from php 7.1 to 7.3
=> Change our default php version from 7.1 to 7.3

package-lock.json, package.json, src/Frontend/Themes/Bootstrap4/src/Layout/Sass/_bootstrap-imports.scss, src/Frontend/Themes/Bootstrap4/src/Layout/Sass/_bootstrap-variables.scss
- Enhancement
You can now use toasts and other features of the newer bootstrap version
Update version of Bootstrap to 4.5
=> Update to Bootstrap 4.5

src/Backend/Core/Engine/Form.php, src/Backend/Form/Type/EditorType.php
Load js that is needed for the editor
=> Fix issues with ck editor

gulpfile.js, js/vendors/bootstrap.bundle.js, src/Frontend/Core/Header/Header.php, src/Frontend/Themes/Bootstrap4/src/Js/Index.js
Bootstrap js was not loaded for main fork js, example in frontend.js. The tooltips for required fields were not working causes that.
We still load bootstap 2 times, once for main frontend js, once for our theme js.
=> Load bootstrap 2 times, once for theme, once for main fork frontend

src/Frontend/Themes/Bootstrap5/src/Layout/Sass/_bootstrap-variables.scss
=> Fix code styles

.gitlab-ci.yml
php 7.3 => php 7.4
mysql 5.5 => mysql 5.7
=> Upgrade php ci

package-lock.json, package.json, src/Frontend/Themes/Bootstrap4/src/Js/Index.js, src/Frontend/Themes/Bootstrap4/src/Js/Utilities/Fancybox.js, src/Frontend/Themes/Bootstrap4/src/Layout/Sass/screen.scss, src/Frontend/Themes/Bootstrap5/src/Js/Index.js, src/Frontend/Themes/Bootstrap5/src/Js/Utilities/Fancybox.js, src/Frontend/Themes/Bootstrap5/src/Layout/Sass/screen.scss
The previous package we used, was the old one and wasn't really updated to the newest version. Intern they still loaded version 2.
=> Use the real fancybox 3

src/Frontend/Themes/Bootstrap4/src/Layout/Templates/PrivacyConsentDialog.html.twig
Checkbox werkt niet als het een custom is zonder die for die het linkt aan het input veld.
=> Fix checkox by adding missing for on label

src/Frontend/Themes/Bootstrap5/src/Layout/Sass/components/_privacyConsentDialog.scss, src/Frontend/Themes/Bootstrap5/src/Layout/Sass/screen.scss, src/Frontend/Themes/Bootstrap5/src/Layout/Templates/Notifications.html.twig, src/Frontend/Themes/Bootstrap5/src/Layout/Templates/PrivacyConsentDialog.html.twig
The consent dialog was not implemented in this theme. So I implemented it. It's a copy of bs4 theme.
=> Add consent dialog bs5 theme

package.json
=> Use Bootstrap4 default

composer.json, composer.lock
Sentry integration seems to be missing
Add sentry package back to composer.json
=> Reintroduce sentry-symfony package

tests/data/test_db.sql
Fixed issue with the SQL dump that prevented the PHPStan job to be executed
=> Fix phpstan issue

.gitlab-ci.yml
Fixes: https://app.activecollab.com/108877/projects/533/tasks/124395
=> Fix CI with docker latest images

.gitignore, .gitlab-ci.yml, composer.json, composer.lock, package.json, phpcs.xml.dist
- Enhancement
Improves the Gitlab CI Pipeline:
* Speed up of the jobs by using the needs keyword, and a separate build job
* Added job to scan JS files with StandardJS
* Added jobs to scan voor security issues in the dependencies
* Added job to check for unfinished code
* Output results into JUNIT, which Gitlab can parse and show in the merge requests
=> Improve ci

src/Frontend/Core/Js/frontend.js, src/Frontend/Themes/Bootstrap/src/Layout/Templates/PrivacyConsentDialog.html.twig
https://app.activecollab.com/108877/projects/62/tasks/120672
=> Improve consent dialog in bs5 theme

src/Frontend/Themes/Bootstrap/src/Layout/Templates/Mails/Default.html.twig
- Enhancement
Remove different color for body, so it's all dark of all white.
Add info text to aware the logo also needs to be visible in dark mode.
=> Better dark light mode layout

src/Frontend/Themes/Bootstrap/src/Layout/Sass/base/_base.scss
- Enhancement
Add max-width and height to img in p tag (added through backend editor)
=> add max-width and height to img p

deploy.php
Fix the test to see if migrations are present in project before executing the database migrations task
=> Fix database migrations for fork in deployer

composer.json, composer.lock, deploy.php
- Enhancement
update to deployer 7
=> 54 update deployer

gulpfile.js, package-lock.json, package.json, src/Frontend/Themes/Bootstrap/src/Layout/Sass/base/_fonts.scss, src/Frontend/Themes/Bootstrap/src/Layout/Sass/screen.scss
- Enhancement
Remove the gulp-fontgen package, commit and copy all font files instead.
=> Remove gulp fontgen

package.json, src/Frontend/Themes/Bootstrap/src/Layout/Sass/screen.scss
Fix bootstrap scss utilities issue when building
=> Fix bootstrap sass utilities issue

.gitlab-ci.yml
Only scan packages that are part of the dependencies, not devDependencies
=> Only scan real dependencies

bin/console, composer.json
Fix deploying with deployer 7
Problems that Davy had in Solar Best Practices
=> Fix deploy 7

.nvmrc, package.json
Update node version to 18 lts/hydrogen
=> Update node version

src/Frontend/Themes/Bootstrap/Modules/Pages/Layout/Widgets/Sitemap.html.twig
Replace absolute paths by relative
`open_basedir restriction in effect`
=> Fix open_basedir errors

deploy.php
=> Lock cachetool version to 7.0.0

src/Frontend/Themes/Bootstrap/src/Layout/Sass/base/_editor-content.scss, src/Frontend/Themes/Bootstrap/src/Layout/Sass/editor_content.scss
- Enhancement
Add editor-content scss files (for backend editor content styling)
=> Add editor content scss files

src/Frontend/Themes/Bootstrap/src/Layout/Sass/components/_navbar-toggler.scss, src/Frontend/Themes/Bootstrap/src/Layout/Sass/screen.scss
- Enhancement
Add animated navbar toggler icon, animating from hamburger to X
=> Add animated navbar-toggler

src/Frontend/Core/Js/frontend.js
- Enhancement
Reload the consent dialog when an element with data-role="show-consent-dialog" is clicked.
=> Change consent preferences

src/Frontend/Themes/Bootstrap/src/Layout/Sass/components/_privacyConsentDialog.scss, src/Frontend/Themes/Bootstrap/src/Layout/Templates/PrivacyConsentDialog.html.twig
- Enhancement
Improve the accessibility of the privacy consent dialog modal
=> Improve PrivacyConsentDialog.html.twig accessibility

deploy.php
- Fix opcache not running
- Use latest version of cachetool possible
=> Fix opcache in deploy

composer.json
Resolves composer install conflicts between deployer-sumo and symfony 4
- Enhancement
=> Bump deployer-sumo, adds symfony 4 support

src/Backend/Modules/MediaLibrary/Domain/MediaItem/MediaItemDataGrid.php, src/Backend/Modules/MediaLibrary/Domain/MediaItem/MediaItemSelectionDataGrid.php
Extra fix for https://github.com/sumocoders/forkcms/pull/388/commits/de179eb231c3b8652e27ff14ee28ceb8c3f0d8b1
=> Fix datagrids for new naming

src/Frontend/Themes/Bootstrap/src/Layout/Templates/Base.html.twig
Add sitehtmlstartofbody tag to custom template
=> Add sitehtmlstartofbody to custom template
