sumocoders/forkcms

- src/Frontend/Themes/Bootstrap/src/Layout/Templates/Head.tpl
Facebook needs a full url to show the image.
> Add site url to image_src path

- src/Backend/Modules/Pages/Js/Pages.js
If our usertemplate had an id bigger then the highest extraId, the visual representation was never shown.
This makes sure this check does not apply to user templates anymore
> Fix usertemplates with high id's

- src/Frontend/Themes/Bootstrap/Modules/FormBuilder/Layout/Widgets/Form.tpl
Show FormBuilder errors with text-danger class because class formError is not used anymore
> Show FormBuilder errors correctly

- src/Frontend/Themes/Bootstrap/src/Layout/Templates/Head.tpl
This avoids mixed content warnings.
> Fetch the IE shims using the currently used protocol.

- src/Frontend/Themes/Bootstrap/src/Layout/Templates/Notifications.html.twig
Link in cookie bar doesn't work without raw modifier: https://cloudup.com/cK1OMh3vjqa
> Fix link in cookie bar text in Bootstrap theme

- src/Frontend/Themes/Bootstrap/src/Layout/Templates/Default.html.twig
- src/Frontend/Themes/Bootstrap/src/Layout/Templates/Error.html.twig
- src/Frontend/Themes/Bootstrap/src/Layout/Templates/Home.html.twig
- src/Frontend/Themes/Bootstrap/src/Layout/Templates/Navbar.html.twig
- src/Frontend/Themes/Bootstrap/src/Layout/Templates/Sidebar.html.twig
Every block is now parsed in php then sent to the template. If it was
getting in the include_path block, this meant that a block outputted
empty html, causing an error to be thrown.
> Don't include widgets anymore.

- src/Frontend/Themes/Bootstrap/src/Js/utilities/distribute-height.js
Not all browsers support the for...of... notation yet, so we went old school again.
> Fix distribute-height utility so it works for all browsers

- composer.json
It will fix issues with composer when trying to add new dependencies. As our
minimum dependency is stable and the flippa-official/errbit-php is not.
> Add Errbit dependency back to composer.json

- src/Frontend/Themes/Bootstrap/Modules/Profiles/Layout/Widgets/LoginBox.html.twig
Use a comma instead of `:` as the separator in a twig function.
> Use a comma as a separator for a twig function

- src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Templates/Archive.html.twig
- src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Templates/Article.html.twig
- src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Templates/Category.html.twig
- src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Templates/Detail.html.twig
- src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Templates/Index.html.twig
- src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Widgets/Archive.html.twig
- src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Widgets/Categories.html.twig
- src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Widgets/RecentArticlesFull.html.twig
- src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Widgets/RecentArticlesList.html.twig
- src/Frontend/Themes/Bootstrap/Modules/Blog/Layout/Widgets/RecentComments.html.twig
- Enhancement
Update the markup of the blog module templates
> Add new layout blog module

- src/Frontend/Themes/Bootstrap/src/Layout/Templates/FormLayout.html.twig
- Enhancement
Symfony forms didn't use boostrap in the frontend
> Add default bootstrap layout for symfony forms

- src/Frontend/Themes/Bootstrap/Modules/Mailmotor/Layout/Templates/Subscribe.html.twig
- src/Frontend/Themes/Bootstrap/Modules/Mailmotor/Layout/Templates/Unsubscribe.html.twig
- src/Frontend/Themes/Bootstrap/Modules/Mailmotor/Layout/Widgets/Subscribe.html.twig
Mailmotor templates were broken cause they didn't use symfony forms
> Use symfony forms in mailmotor templates

- src/Frontend/Themes/Bootstrap/src/Layout/Templates/Pagination.html.twig
if the pagination was more than 7 items the last number didn't show because a wrong template parameter was used
> Fix last label in big paginations not showing

- src/Frontend/Core/Header/Header.php
- src/Frontend/Core/Header/MetaCollection.php
- Feature
https://app.activecollab.com/108877/reports/assignments?modal=Task-30843-860
Websites with hostname like *.sumocoders.eu should have a no-index meta tag.
> Add no-index automatically if host *.sumocoders.eu

- app/AppKernel.php
- app/config/config_prod.yml
- app/config/parameters.yml.dist
- composer.json
- composer.lock
- Feature
Errbit package used in [sumo-fork-class](https://github.com/sumocoders/Sumo-specific-Fork-stuff) currently doesn't work with Fork 5. Sentry is presented here as an alternative to Errbit.
> Sentry integration

- Capfile
The Capistrano log file is being written to app/logs instead of var/logs as it is currently standard in Symfony 3.
> Move capistrano log destination to var/

- .gitlab-ci.yml
The ci fails because the filename is wrong
> The generate_parameters_gitlab file doesn't have the .php extension

- src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Notifications.html.twig
Cookiebar actions do not work, cause they do not have the correct data attributes
> Add new data attributes to make cookiebar actions work agian

- src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Notifications.html.twig
- Enhancement
Layout cookiebar mobile bad, text and buttons were really close to each other
> Move cookiebar buttons on new line on mobile

- app/config/config.yml
- Enhancement
This PR enables log rotation using Monolog. The log rotates every day and logs from previous days are kept to a maximum of 10 files.
> Enable monolog rotating file log mode.

- package.json
This PR changes the nodejs engine required version from 7 to 8.
> Change node engine version from 7 to 8

- package.json
- src/Frontend/Themes/Bootstrap4/src/Js/Index.js
- src/Frontend/Themes/Bootstrap4/src/Js/Utilities/ScrollTo.js
Fix blank page in chrome. After an update of chrome to v67, sweet scroll causes this issue.
> Remove sweetscroll and use our own scroll to method

- src/Frontend/Themes/Bootstrap4/src/Layout/Sass/base/_base.scss
- src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Notifications.html.twig
- Enhancement
Improve accessibility by make the skip to content link visible on focus.
> Make skip to content link visible on focus

- gulpfile.js
Our deployment uses the gulp task `build:theme` which was removed by updating Gulp.
Re-add `build:theme` gulp task.
> Re-add gulp build:theme task because it is used for deployment

- index.php
The headers of the proxy on staging aren't forwarded. Because of this https isn't detected.
This fixes that issue
> Fix proxy issues on staging

- src/Frontend/Themes/Bootstrap4/src/Layout/Templates/FormLayout.html.twig
We were still using form layout from bootstrap 3, we are now using 4
> Update the base of the form layout to bs4

- src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Detail.html.twig
Put the error after the form input field on the detail page of a blog item, so that it is the same as everywhere else in Fork.
> Put the error after the field on blog detail page

- src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Base.html.twig
If the addTimestamp option was set true with the addJS function i wasn't working because of the way we rendered the script tags in the template
> Make adding a timestamp in the php work

- .gitlab-ci.yml
PHPStan requires more memory than 512MB which is set by default on our images.
At the same time there were a lot of job that exited with a 137 code. Which indicated our runners ran out of memory. After some digging around I think it was related to:
* https://gitlab.com/gitlab-org/gitlab-runner/issues/3816#note_149184430
* https://gitlab.com/gitlab-org/gitlab-runner/issues/3816#note_132190195
We were using `https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/coreos-stable-2135-6-0-v20190801` hardcoded in our `/etc/gitlab/config.toml`. By replacing this with `https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/family/coreos-stable` our runners will use the latest stable release of CoreOS.
> Increase memory for PHPStan

- src/Frontend/Themes/Bootstrap4/Modules/Profiles/Layout/Templates/ForgotPassword.html.twig
The wrong class breaks the layout, `input-group-append` is what we now use with Bootstrap 4
> Use correct input group class

- src/Frontend/Themes/Bootstrap4/Modules/Blog/Layout/Templates/Index.html.twig
- Enhancement
We do not need to use `|batch` because with bootstrap 4 (flexbox) we can set equal height per visual row
> Remove batched items

- app/config/config_prod.yml
Fixes SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13)
- Enhancement
- Feature
> Fix session files cleanup errors on Debian

- src/Frontend/Themes/Bootstrap4/src/Layout/Templates/Error.html.twig
Unexisting image in error template
Changes the image to one that is in the project and get rid of the incorrect divs arround is (row div but no col div).
> Fix image in error template

- package-lock.json
- package.json
Font awesome 4 is still used in the backend so can't be removed yet
> Readd font awesome because it's use in the backend

- src/Frontend/Themes/Bootstrap4/src/Layout/Sass/components/_footer.scss
Fix sticky footer to much whitespace caused by resized images in the content (in Internet Explorer)
> Fix sticky footer to much whitespace

- deploy.php
- set releases to 3 for production and staging
- set port to 2244 for production
- set writable_mode and http_user for production (no setfacl on cloudstar hosting)
- set deploy_path and document_root for production
- set bin/cachetool for production (as default is for php8), must be manually downloaded
- set cachetool for production
> Update deploy file for cloudstar hosting

- src/Frontend/Themes/Bootstrap/src/Layout/Templates/FormLayout.html.twig
- src/Frontend/Themes/Bootstrap/src/Layout/Templates/FormLayouts/bootstrap_5_layout.html.twig
New project, had error:
`Template "FormLayouts/bootstrap_5_layout.html.twig" is not defined.`
when was fixed, another:
`Unknown "form_help" function. Did you mean "form_rest", "form_end"?`
when fixed, another:
`The merge filter only works with arrays or "Traversable", got "NULL" as first argument in "Core/Layout/Templates/FormLayouts/bootstrap_5_layout.html.twig".`
> Fix boostrap5 theme for forms

- src/Backend/Core/Js/backend.js
- Enhancement
Too many styles are shown in CKEditor:
* Removed default frontend fork style sheets from the list of stylesheets that should be parsed for styles
* Make sure `select` and `textarea` selectors are skipped
> Limit styles in CKEditor

- src/Frontend/Modules/FormBuilder/Widgets/Form.php
- src/Frontend/Themes/Bootstrap/Modules/FormBuilder/Layout/Widgets/Form.html.twig
Add bootstrap 5 classes to the formbuilder inputs to make sure they are rendered correctly.
> Add bootstrap 5 classes to formbuilder inputs

- .htaccess
Ogone uses the Indy Library user agent, which is blocked by default
> Remove Indy Library blocking

- src/Backend/Modules/Pages/Installer/Data/bg/404.txt
- src/Backend/Modules/Pages/Installer/Data/cs/404.txt
- src/Backend/Modules/Pages/Installer/Data/de/404.txt
- src/Backend/Modules/Pages/Installer/Data/el/404.txt
- src/Backend/Modules/Pages/Installer/Data/en/404.txt
- src/Backend/Modules/Pages/Installer/Data/es/404.txt
- src/Backend/Modules/Pages/Installer/Data/fr/404.txt
- src/Backend/Modules/Pages/Installer/Data/hu/404.txt
- src/Backend/Modules/Pages/Installer/Data/it/404.txt
- src/Backend/Modules/Pages/Installer/Data/ja/404.txt
- src/Backend/Modules/Pages/Installer/Data/lt/404.txt
- src/Backend/Modules/Pages/Installer/Data/nl/404.txt
- src/Backend/Modules/Pages/Installer/Data/pl/404.txt
- src/Backend/Modules/Pages/Installer/Data/pt/404.txt
- src/Backend/Modules/Pages/Installer/Data/ro/404.txt
- src/Backend/Modules/Pages/Installer/Data/ru/404.txt
- src/Backend/Modules/Pages/Installer/Data/sv/404.txt
- src/Backend/Modules/Pages/Installer/Data/tr/404.txt
- src/Backend/Modules/Pages/Installer/Data/uk/404.txt
- src/Backend/Modules/Pages/Installer/Data/zh/404.txt
- src/Backend/Modules/Pages/Installer/Installer.php
- src/Frontend/Themes/Bootstrap/src/Layout/Sass/components/_error.scss
- src/Frontend/Themes/Bootstrap/src/Layout/Sass/screen.scss
- src/Frontend/Themes/Bootstrap/src/Layout/Templates/Error.html.twig
- Enhancement
Restyle default error page (404):
- remove sitemap
- update styling
> 477 update 404 page

- src/Backend/Modules/Pages/Ajax/UploadFile.php
Internal link: https://app.activecollab.com/108877/reports/assignments?modal=Task-204045-62
Add time to filenames for user template images. So they have unique filenames and other user templates (with same image) don't break when you change an image to a different one.
> Add time to user template images to make unique filesnames

- src/Backend/Modules/Pages/Ajax/RemoveUploadedFile.php
- src/Backend/Modules/Pages/Js/Pages.js
Internal link: https://app.activecollab.com/108877/reports/assignments?modal=Task-208932-62
When there is no old image, the whole UserTemplate directory gets deleted
> Fix delete user template directory

- .stylelintrc
- Enhancement
Fixes issues with stylelint incorrectly parsing scss files
Update .stylelintrc to use scss config and ignore no-descending-specificity rule (throws errors with nesting in scss that wil be solved on compile)
> Update stylelintrc to support scss
